package MasterMind;

abstract public class MasterMindStrategy {
    protected int m_amountColorsGame;
    protected int m_colsGame;
    
    public MasterMindStrategy(int amountColors, int cols){
        m_amountColorsGame = amountColors;
        m_colsGame = cols;
    }
    
    /**
     * Guesses the code (for code breaker)
     * @return the guessed code generated by the strategy
     */
    abstract public Code guessCode();

    /**
     * Generates a code (for codemaker)
     * @return the code generated by the strategy
     */
    abstract public Code generateCode();
}